<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema"
                  xmlns:tns="http://www.jcv.com/addEmployee"
                  targetNamespace="http://www.jcv.com/addEmployee">

    <!-- Referencia al esquema XSD externo -->
    <wsdl:types>
        <xs:schema targetNamespace="http://www.jcv.com/addEmployee" elementFormDefault="qualified">
            <xs:import namespace="http://www.jcv.com/addEmployee"
                       schemaLocation="https://jcvalerovergara.github.io/employee-wsdl/xsd/employee.xsd"/>
        </xs:schema>
    </wsdl:types>

    <!-- Mensajes del servicio -->
    <wsdl:message name="AddEmployeeRequestMessage">
        <wsdl:part name="parameters" element="tns:AddEmployeeRequest"/>
    </wsdl:message>

    <wsdl:message name="AddEmployeeResponseMessage">
        <wsdl:part name="parameters" element="tns:AddEmployeeResponse"/>
    </wsdl:message>

    <!-- Puerto y binding -->
    <wsdl:portType name="AddEmployeePortType">
        <wsdl:operation name="AddEmployee">
            <wsdl:input message="tns:AddEmployeeRequestMessage"/>
            <wsdl:output message="tns:AddEmployeeResponseMessage"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="AddEmployeeBinding" type="tns:AddEmployeePortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="AddEmployee">
            <soap:operation soapAction="http://www.jcv.com/addEmployee/AddEmployee"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <!-- Servicio -->
    <wsdl:service name="AddEmployeeService">
        <wsdl:port name="AddEmployeePort" binding="tns:AddEmployeeBinding">
            <soap:address location="http://localhost:8080/ws/addEmployee"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
